spring.application.name=daybyday

# Configuration de la base de données MySQL
spring.datasource.url=jdbc:mysql://localhost:3306/daybyday
spring.datasource.username=root
spring.datasource.password=" "

# Le dialecte pour MySQL
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

# DDL auto (crée ou met à jour les tables en fonction des entités)
spring.jpa.hibernate.ddl-auto=validate
server.port=8080

# Afficher les requêtes SQL dans la console
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Encodage UTF-8 pour éviter les problèmes avec les caractères spéciaux
spring.datasource.hikari.connection-init-sql=SET NAMES utf8mb4 COLLATE utf8mb4_unicode_ci
